import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';

import '../../../utils.dart';

part 'filtrarmarcas_bloc_state.dart';

class FiltrarMarcasBlocCubit extends Cubit<FiltrarMarcasBlocState> {
  
  // List<String> list =[];

  FiltrarMarcasBlocCubit() : super(FiltrarMarcasInitial()){
    getMarcas('');
  }

  Future<void> getMarcas(String filtro)  async {
    emit(FiltrarMarcasLoading());

    try {

      if (filtro.trim().length > 0) {
        
        var listaFiltrada = marcas.where((item) => Utils.removerAcentos(item.toLowerCase()).contains(Utils.removerAcentos(filtro.toLowerCase()))).toList();
        
        emit(FiltrarMarcasLoaded(list: listaFiltrada));
      }
      else{
        emit(FiltrarMarcasLoaded(list: []));
      }
      
    } catch (e) {
      emit(FiltrarMarcasError(message: "Não foi possível recuperar os dados"));
    }
  }

  List<String> marcas = [
    'Acura',
    'Agrale',
    'Alfa Romeo',
    'Asia',
    'AM General',
    'Aston Martin',
    'Audi',
    'Adly',
    'Aprilia',
    'Atala',
    'Amazonas',
    'Austin',
    'Apperson',
    'Ashok Leyland',
    'Alpina',
    'Adler',
    'Ascari',
    'Abarth',
    'Autobianchi',
    'Aixam',
    'AMG',
    'AZLK',
    'Avtokam',
    'ACMAT',
    'Albion',
    'Argyle',
    'Askam',
    'Aspark Owl',
    'A.D. Tramontana',
    'BMW',
    'Buggy',
    'BRM',
    'Bugre',
    'Bugatti',
    'Bentley',
    'Buick',
    'Baker',
    'Biddle',
    'Bajaj',
    'Bitter',
    'Borgward',
    'Briggs',
    'Belsize',
    'Bertone',
    'Bianchi',
    'Brilliance',
    'Byd Auto',
    'Baic',
    'Birrana',
    'Brabus',
    'Birkin',
    'Bailey',
    'Chevrolet',
    'Cadillac',
    'CBT',
    'Chana',
    'Changan',
    'Chery',
    'Chrysler',
    'Citroen',
    'Cross Lander',
    'Chinkara',
    'Caterham',
    'Chater-Lea',
    'Covini',
    'Caresto',
    'Changhe',
    'Cizeta',
    'Daewoo',
    'Daihatsu',
    'Dodge',
    'De Tomaso',
    'Delorean',
    'DKW',
    'DR Motor',
    'De La Chapelle',
    'Dongfeng',
    'DRB',
    'Derways',
    'Dragon Motors',
    'Daimler',
    'Datsun',
    'Dacia',
    'DoniRosset',
    'Ducati',
    'Effa',
    'Engesa',
    'Envemo',
    'Eicher',
    'Esther',
    'Elfin',
    'Eagle',
    'Eterniti',
    'ERF',
    'Elva',
    'Ferrari',
    'FIAT',
    'Fibravan',
    'Ford',
    'Foton',
    'Fyber',
    'Force',
    'Fornasari',
    'Fisker',
    'Freightliner',
    'Faw',
    'FPV',
    'Facel Vega',
    'Fioravanti',
    'Franklin',
    'Geely',
    'GM',
    'Great Wall',
    'Gurgel',
    'GMC',
    'Gorhan',
    'Gumpert',
    'Ginetta',
    'Geo',
    'GAC',
    'Giocattolo',
    'Gaz',
    'Genesis',
    'Gillet',
    'Grinnall',
    'Hafei',
    'Harley-Davidson',
    'Honda',
    'Hyundai',
    'Husqvarna',
    'Hummer',
    'Hindustan',
    'Hongqi',
    'Holden',
    'HSV',
    'Hino',
    'Harper',
    'Hero Motors',
    'Isuzu',
    'Iveco',
    'ICML Motors',
    'Infiniti',
    'Isdera',
    'Invicta',
    'Isotta Fraschini',
    'Irizar',
    'Innoson',
    'Ivema',
    'Jeep',
    'Jaguar',
    'JPX',
    'Jinbei',
    'JAC',
    'James & Browne',
    'Josse Car',
    'Jiefang',
    'Kawasaki',
    'Kia',
    'Kahena',
    'Kasinski',
    'KTM',
    'Keinath',
    'Koenigsegg',
    'Kamaz',
    'Kawasaki',
    'Karma',
    'Kaz',
    'Karrier',
    'Kantanka',
    'Kiira',
    'Lada',
    'Lamborghini',
    'Lancia',
    'Land Rover',
    'Lexus',
    'Lifan',
    'Lotus',
    'Lobini',
    'Lincoln',
    'Laferrari',
    'Ligier',
    'Lagonda',
    'Lucid',
    'Luxgen',
    'Laraki',
    'Mahindra',
    'Maserati',
    'Matra',
    'MG',
    'Mazda',
    'Mclaren',
    'Mercedes-Benz',
    'Mercury',
    'Miura',
    'Mini',
    'Mitsubishi',
    'Maruti',
    'Mitsuoka',
    'Maybach',
    'Microcar',
    'Mack',
    'Moskvich',
    'Marussia',
    'MAN',
    'Marcos',
    'Mazzanti',
    'Morris',
    'Mustang',
    'MAZ',
    'Mobius',
    'Nissan',
    'Navistar',
    'Nota',
    'Nami Okhta',
    'Noble',
    'Opel',
    'Oldsmobile',
    'Ohta Jidosha',
    'Otosan',
    'ÖAF',
    'Peugeot',
    'Plymouth',
    'Pontiac',
    'Porsche',
    'Puma',
    'Polaris',
    'Panoz',
    'Premier',
    'Prince',
    'Pagani',
    'Panhard',
    'PGO',
    'Pyeonghwa',
    'Proto',
    'Perodua',
    'Paccar',
    'Pininfarina',
    'Paramount Automotive',
    'Proforce',
    'Perana',
    'RAM',
    'Rely',
    'Rover',
    'Renault',
    'Rolls-Royce',
    'Rootes',
    'Rambler',
    'Riley',
    'Rossion',
    'RUF',
    'Ronart',
    'Rimac',
    'SAAB',
    'Saturn',
    'SEAT',
    'Shineray',
    'Smart',
    'Ssangyong',
    'Subaru',
    'Suzuki',
    'Sundown',
    'Sino Truck',
    'Scania',
    'Scion',
    'Saic',
    'Spetsteh',
    'Skoda',
    'Shelby',
    'Saleen',
    'Sterling',
    'Saroukh El-jamahiriya',
    'Shaka Nynya',
    'TAC',
    'Toyota',
    'Troller',
    'Tata',
    'Triumph',
    'Traxx',
    'Tesla',
    'Tatra',
    'Trion',
    'Triumph',
    'The Turtle',
    'Tropical',
    'UAZ',
    'Unimog',
    'UEV',
    'Ultima',
    'Uri',
    'URO',
    'Volvo',
    'Volkswagen',
    'Venturi',
    'Volga',
    'Vauxhall',
    'Vector',
    'Venucia',
    'Vulcan',
    'Vomag',
    'Vanaja',
    'Wake',
    'Walk',
    'Wuyang',
    'Wheego',
    'Willeme',
    'Wallys',
    'Yamaha'
  ];
}
